package com.happy.otc.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asset.proto

public final class Asset {
  private Asset() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AssetDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AssetDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double capitalAvailable = 1;</code>
     */
    double getCapitalAvailable();

    /**
     * <code>double capitalBalance = 2;</code>
     */
    double getCapitalBalance();

    /**
     * <code>double capitalFrozen = 3;</code>
     */
    double getCapitalFrozen();

    /**
     * <code>int64 capitalId = 4;</code>
     */
    long getCapitalId();

    /**
     * <code>int64 currencyId = 5;</code>
     */
    long getCurrencyId();

    /**
     * <code>string currencySimpleName = 6;</code>
     */
    String getCurrencySimpleName();
    /**
     * <code>string currencySimpleName = 6;</code>
     */
    com.google.protobuf.ByteString
        getCurrencySimpleNameBytes();

    /**
     * <code>int64 userId = 7;</code>
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code AssetDTO}
   */
  public  static final class AssetDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AssetDTO)
      AssetDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AssetDTO.newBuilder() to construct.
    private AssetDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AssetDTO() {
      capitalAvailable_ = 0D;
      capitalBalance_ = 0D;
      capitalFrozen_ = 0D;
      capitalId_ = 0L;
      currencyId_ = 0L;
      currencySimpleName_ = "";
      userId_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AssetDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              capitalAvailable_ = input.readDouble();
              break;
            }
            case 17: {

              capitalBalance_ = input.readDouble();
              break;
            }
            case 25: {

              capitalFrozen_ = input.readDouble();
              break;
            }
            case 32: {

              capitalId_ = input.readInt64();
              break;
            }
            case 40: {

              currencyId_ = input.readInt64();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              currencySimpleName_ = s;
              break;
            }
            case 56: {

              userId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Asset.internal_static_AssetDTO_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Asset.internal_static_AssetDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AssetDTO.class, Builder.class);
    }

    public static final int CAPITALAVAILABLE_FIELD_NUMBER = 1;
    private double capitalAvailable_;
    /**
     * <code>double capitalAvailable = 1;</code>
     */
    public double getCapitalAvailable() {
      return capitalAvailable_;
    }

    public static final int CAPITALBALANCE_FIELD_NUMBER = 2;
    private double capitalBalance_;
    /**
     * <code>double capitalBalance = 2;</code>
     */
    public double getCapitalBalance() {
      return capitalBalance_;
    }

    public static final int CAPITALFROZEN_FIELD_NUMBER = 3;
    private double capitalFrozen_;
    /**
     * <code>double capitalFrozen = 3;</code>
     */
    public double getCapitalFrozen() {
      return capitalFrozen_;
    }

    public static final int CAPITALID_FIELD_NUMBER = 4;
    private long capitalId_;
    /**
     * <code>int64 capitalId = 4;</code>
     */
    public long getCapitalId() {
      return capitalId_;
    }

    public static final int CURRENCYID_FIELD_NUMBER = 5;
    private long currencyId_;
    /**
     * <code>int64 currencyId = 5;</code>
     */
    public long getCurrencyId() {
      return currencyId_;
    }

    public static final int CURRENCYSIMPLENAME_FIELD_NUMBER = 6;
    private volatile Object currencySimpleName_;
    /**
     * <code>string currencySimpleName = 6;</code>
     */
    public String getCurrencySimpleName() {
      Object ref = currencySimpleName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        currencySimpleName_ = s;
        return s;
      }
    }
    /**
     * <code>string currencySimpleName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencySimpleNameBytes() {
      Object ref = currencySimpleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        currencySimpleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 7;
    private long userId_;
    /**
     * <code>int64 userId = 7;</code>
     */
    public long getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (capitalAvailable_ != 0D) {
        output.writeDouble(1, capitalAvailable_);
      }
      if (capitalBalance_ != 0D) {
        output.writeDouble(2, capitalBalance_);
      }
      if (capitalFrozen_ != 0D) {
        output.writeDouble(3, capitalFrozen_);
      }
      if (capitalId_ != 0L) {
        output.writeInt64(4, capitalId_);
      }
      if (currencyId_ != 0L) {
        output.writeInt64(5, currencyId_);
      }
      if (!getCurrencySimpleNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, currencySimpleName_);
      }
      if (userId_ != 0L) {
        output.writeInt64(7, userId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (capitalAvailable_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, capitalAvailable_);
      }
      if (capitalBalance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, capitalBalance_);
      }
      if (capitalFrozen_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, capitalFrozen_);
      }
      if (capitalId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, capitalId_);
      }
      if (currencyId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, currencyId_);
      }
      if (!getCurrencySimpleNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, currencySimpleName_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AssetDTO)) {
        return super.equals(obj);
      }
      AssetDTO other = (AssetDTO) obj;

      boolean result = true;
      result = result && (
          Double.doubleToLongBits(getCapitalAvailable())
          == Double.doubleToLongBits(
              other.getCapitalAvailable()));
      result = result && (
          Double.doubleToLongBits(getCapitalBalance())
          == Double.doubleToLongBits(
              other.getCapitalBalance()));
      result = result && (
          Double.doubleToLongBits(getCapitalFrozen())
          == Double.doubleToLongBits(
              other.getCapitalFrozen()));
      result = result && (getCapitalId()
          == other.getCapitalId());
      result = result && (getCurrencyId()
          == other.getCurrencyId());
      result = result && getCurrencySimpleName()
          .equals(other.getCurrencySimpleName());
      result = result && (getUserId()
          == other.getUserId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CAPITALAVAILABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getCapitalAvailable()));
      hash = (37 * hash) + CAPITALBALANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getCapitalBalance()));
      hash = (37 * hash) + CAPITALFROZEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getCapitalFrozen()));
      hash = (37 * hash) + CAPITALID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCapitalId());
      hash = (37 * hash) + CURRENCYID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrencyId());
      hash = (37 * hash) + CURRENCYSIMPLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencySimpleName().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AssetDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AssetDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AssetDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AssetDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AssetDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AssetDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AssetDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AssetDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AssetDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AssetDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AssetDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AssetDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AssetDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AssetDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AssetDTO)
        AssetDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Asset.internal_static_AssetDTO_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Asset.internal_static_AssetDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AssetDTO.class, Builder.class);
      }

      // Construct using Asset.AssetDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        capitalAvailable_ = 0D;

        capitalBalance_ = 0D;

        capitalFrozen_ = 0D;

        capitalId_ = 0L;

        currencyId_ = 0L;

        currencySimpleName_ = "";

        userId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Asset.internal_static_AssetDTO_descriptor;
      }

      public AssetDTO getDefaultInstanceForType() {
        return AssetDTO.getDefaultInstance();
      }

      public AssetDTO build() {
        AssetDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AssetDTO buildPartial() {
        AssetDTO result = new AssetDTO(this);
        result.capitalAvailable_ = capitalAvailable_;
        result.capitalBalance_ = capitalBalance_;
        result.capitalFrozen_ = capitalFrozen_;
        result.capitalId_ = capitalId_;
        result.currencyId_ = currencyId_;
        result.currencySimpleName_ = currencySimpleName_;
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AssetDTO) {
          return mergeFrom((AssetDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AssetDTO other) {
        if (other == AssetDTO.getDefaultInstance()) return this;
        if (other.getCapitalAvailable() != 0D) {
          setCapitalAvailable(other.getCapitalAvailable());
        }
        if (other.getCapitalBalance() != 0D) {
          setCapitalBalance(other.getCapitalBalance());
        }
        if (other.getCapitalFrozen() != 0D) {
          setCapitalFrozen(other.getCapitalFrozen());
        }
        if (other.getCapitalId() != 0L) {
          setCapitalId(other.getCapitalId());
        }
        if (other.getCurrencyId() != 0L) {
          setCurrencyId(other.getCurrencyId());
        }
        if (!other.getCurrencySimpleName().isEmpty()) {
          currencySimpleName_ = other.currencySimpleName_;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AssetDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AssetDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double capitalAvailable_ ;
      /**
       * <code>double capitalAvailable = 1;</code>
       */
      public double getCapitalAvailable() {
        return capitalAvailable_;
      }
      /**
       * <code>double capitalAvailable = 1;</code>
       */
      public Builder setCapitalAvailable(double value) {
        
        capitalAvailable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double capitalAvailable = 1;</code>
       */
      public Builder clearCapitalAvailable() {
        
        capitalAvailable_ = 0D;
        onChanged();
        return this;
      }

      private double capitalBalance_ ;
      /**
       * <code>double capitalBalance = 2;</code>
       */
      public double getCapitalBalance() {
        return capitalBalance_;
      }
      /**
       * <code>double capitalBalance = 2;</code>
       */
      public Builder setCapitalBalance(double value) {
        
        capitalBalance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double capitalBalance = 2;</code>
       */
      public Builder clearCapitalBalance() {
        
        capitalBalance_ = 0D;
        onChanged();
        return this;
      }

      private double capitalFrozen_ ;
      /**
       * <code>double capitalFrozen = 3;</code>
       */
      public double getCapitalFrozen() {
        return capitalFrozen_;
      }
      /**
       * <code>double capitalFrozen = 3;</code>
       */
      public Builder setCapitalFrozen(double value) {
        
        capitalFrozen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double capitalFrozen = 3;</code>
       */
      public Builder clearCapitalFrozen() {
        
        capitalFrozen_ = 0D;
        onChanged();
        return this;
      }

      private long capitalId_ ;
      /**
       * <code>int64 capitalId = 4;</code>
       */
      public long getCapitalId() {
        return capitalId_;
      }
      /**
       * <code>int64 capitalId = 4;</code>
       */
      public Builder setCapitalId(long value) {
        
        capitalId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 capitalId = 4;</code>
       */
      public Builder clearCapitalId() {
        
        capitalId_ = 0L;
        onChanged();
        return this;
      }

      private long currencyId_ ;
      /**
       * <code>int64 currencyId = 5;</code>
       */
      public long getCurrencyId() {
        return currencyId_;
      }
      /**
       * <code>int64 currencyId = 5;</code>
       */
      public Builder setCurrencyId(long value) {
        
        currencyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 currencyId = 5;</code>
       */
      public Builder clearCurrencyId() {
        
        currencyId_ = 0L;
        onChanged();
        return this;
      }

      private Object currencySimpleName_ = "";
      /**
       * <code>string currencySimpleName = 6;</code>
       */
      public String getCurrencySimpleName() {
        Object ref = currencySimpleName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          currencySimpleName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string currencySimpleName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCurrencySimpleNameBytes() {
        Object ref = currencySimpleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          currencySimpleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencySimpleName = 6;</code>
       */
      public Builder setCurrencySimpleName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencySimpleName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencySimpleName = 6;</code>
       */
      public Builder clearCurrencySimpleName() {
        
        currencySimpleName_ = getDefaultInstance().getCurrencySimpleName();
        onChanged();
        return this;
      }
      /**
       * <code>string currencySimpleName = 6;</code>
       */
      public Builder setCurrencySimpleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencySimpleName_ = value;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 7;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 7;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 7;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AssetDTO)
    }

    // @@protoc_insertion_point(class_scope:AssetDTO)
    private static final AssetDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AssetDTO();
    }

    public static AssetDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AssetDTO>
        PARSER = new com.google.protobuf.AbstractParser<AssetDTO>() {
      public AssetDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AssetDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AssetDTO> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AssetDTO> getParserForType() {
      return PARSER;
    }

    public AssetDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PageResultAssetDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PageResultAssetDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 pageSize = 1;</code>
     */
    int getPageSize();

    /**
     * <code>int64 totalResults = 2;</code>
     */
    long getTotalResults();

    /**
     * <code>int32 currentPage = 3;</code>
     */
    int getCurrentPage();

    /**
     * <code>int32 totalPage = 4;</code>
     */
    int getTotalPage();

    /**
     * <code>bool hasNext = 5;</code>
     */
    boolean getHasNext();

    /**
     * <code>bool hasPrevious = 6;</code>
     */
    boolean getHasPrevious();

    /**
     * <code>bool success = 7;</code>
     */
    boolean getSuccess();

    /**
     * <code>int32 code = 8;</code>
     */
    int getCode();

    /**
     * <code>string message = 9;</code>
     */
    String getMessage();
    /**
     * <code>string message = 9;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>string serverTime = 10;</code>
     */
    String getServerTime();
    /**
     * <code>string serverTime = 10;</code>
     */
    com.google.protobuf.ByteString
        getServerTimeBytes();

    /**
     * <code>repeated .AssetDTO data = 11;</code>
     */
    java.util.List<AssetDTO>
        getDataList();
    /**
     * <code>repeated .AssetDTO data = 11;</code>
     */
    AssetDTO getData(int index);
    /**
     * <code>repeated .AssetDTO data = 11;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .AssetDTO data = 11;</code>
     */
    java.util.List<? extends AssetDTOOrBuilder>
        getDataOrBuilderList();
    /**
     * <code>repeated .AssetDTO data = 11;</code>
     */
    AssetDTOOrBuilder getDataOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code PageResultAssetDTO}
   */
  public  static final class PageResultAssetDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PageResultAssetDTO)
      PageResultAssetDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PageResultAssetDTO.newBuilder() to construct.
    private PageResultAssetDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PageResultAssetDTO() {
      pageSize_ = 0;
      totalResults_ = 0L;
      currentPage_ = 0;
      totalPage_ = 0;
      hasNext_ = false;
      hasPrevious_ = false;
      success_ = false;
      code_ = 0;
      message_ = "";
      serverTime_ = "";
      data_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PageResultAssetDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              pageSize_ = input.readInt32();
              break;
            }
            case 16: {

              totalResults_ = input.readInt64();
              break;
            }
            case 24: {

              currentPage_ = input.readInt32();
              break;
            }
            case 32: {

              totalPage_ = input.readInt32();
              break;
            }
            case 40: {

              hasNext_ = input.readBool();
              break;
            }
            case 48: {

              hasPrevious_ = input.readBool();
              break;
            }
            case 56: {

              success_ = input.readBool();
              break;
            }
            case 64: {

              code_ = input.readInt32();
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              serverTime_ = s;
              break;
            }
            case 90: {
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
                data_ = new java.util.ArrayList<AssetDTO>();
                mutable_bitField0_ |= 0x00000400;
              }
              data_.add(
                  input.readMessage(AssetDTO.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Asset.internal_static_PageResultAssetDTO_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Asset.internal_static_PageResultAssetDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PageResultAssetDTO.class, Builder.class);
    }

    private int bitField0_;
    public static final int PAGESIZE_FIELD_NUMBER = 1;
    private int pageSize_;
    /**
     * <code>int32 pageSize = 1;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    public static final int TOTALRESULTS_FIELD_NUMBER = 2;
    private long totalResults_;
    /**
     * <code>int64 totalResults = 2;</code>
     */
    public long getTotalResults() {
      return totalResults_;
    }

    public static final int CURRENTPAGE_FIELD_NUMBER = 3;
    private int currentPage_;
    /**
     * <code>int32 currentPage = 3;</code>
     */
    public int getCurrentPage() {
      return currentPage_;
    }

    public static final int TOTALPAGE_FIELD_NUMBER = 4;
    private int totalPage_;
    /**
     * <code>int32 totalPage = 4;</code>
     */
    public int getTotalPage() {
      return totalPage_;
    }

    public static final int HASNEXT_FIELD_NUMBER = 5;
    private boolean hasNext_;
    /**
     * <code>bool hasNext = 5;</code>
     */
    public boolean getHasNext() {
      return hasNext_;
    }

    public static final int HASPREVIOUS_FIELD_NUMBER = 6;
    private boolean hasPrevious_;
    /**
     * <code>bool hasPrevious = 6;</code>
     */
    public boolean getHasPrevious() {
      return hasPrevious_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 7;
    private boolean success_;
    /**
     * <code>bool success = 7;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int CODE_FIELD_NUMBER = 8;
    private int code_;
    /**
     * <code>int32 code = 8;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 9;
    private volatile Object message_;
    /**
     * <code>string message = 9;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 9;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERTIME_FIELD_NUMBER = 10;
    private volatile Object serverTime_;
    /**
     * <code>string serverTime = 10;</code>
     */
    public String getServerTime() {
      Object ref = serverTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverTime_ = s;
        return s;
      }
    }
    /**
     * <code>string serverTime = 10;</code>
     */
    public com.google.protobuf.ByteString
        getServerTimeBytes() {
      Object ref = serverTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 11;
    private java.util.List<AssetDTO> data_;
    /**
     * <code>repeated .AssetDTO data = 11;</code>
     */
    public java.util.List<AssetDTO> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .AssetDTO data = 11;</code>
     */
    public java.util.List<? extends AssetDTOOrBuilder>
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .AssetDTO data = 11;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .AssetDTO data = 11;</code>
     */
    public AssetDTO getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .AssetDTO data = 11;</code>
     */
    public AssetDTOOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pageSize_ != 0) {
        output.writeInt32(1, pageSize_);
      }
      if (totalResults_ != 0L) {
        output.writeInt64(2, totalResults_);
      }
      if (currentPage_ != 0) {
        output.writeInt32(3, currentPage_);
      }
      if (totalPage_ != 0) {
        output.writeInt32(4, totalPage_);
      }
      if (hasNext_ != false) {
        output.writeBool(5, hasNext_);
      }
      if (hasPrevious_ != false) {
        output.writeBool(6, hasPrevious_);
      }
      if (success_ != false) {
        output.writeBool(7, success_);
      }
      if (code_ != 0) {
        output.writeInt32(8, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, message_);
      }
      if (!getServerTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, serverTime_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(11, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pageSize_);
      }
      if (totalResults_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, totalResults_);
      }
      if (currentPage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, currentPage_);
      }
      if (totalPage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, totalPage_);
      }
      if (hasNext_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, hasNext_);
      }
      if (hasPrevious_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, hasPrevious_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, success_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, message_);
      }
      if (!getServerTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, serverTime_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, data_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PageResultAssetDTO)) {
        return super.equals(obj);
      }
      PageResultAssetDTO other = (PageResultAssetDTO) obj;

      boolean result = true;
      result = result && (getPageSize()
          == other.getPageSize());
      result = result && (getTotalResults()
          == other.getTotalResults());
      result = result && (getCurrentPage()
          == other.getCurrentPage());
      result = result && (getTotalPage()
          == other.getTotalPage());
      result = result && (getHasNext()
          == other.getHasNext());
      result = result && (getHasPrevious()
          == other.getHasPrevious());
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && (getCode()
          == other.getCode());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getServerTime()
          .equals(other.getServerTime());
      result = result && getDataList()
          .equals(other.getDataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (37 * hash) + TOTALRESULTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalResults());
      hash = (37 * hash) + CURRENTPAGE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentPage();
      hash = (37 * hash) + TOTALPAGE_FIELD_NUMBER;
      hash = (53 * hash) + getTotalPage();
      hash = (37 * hash) + HASNEXT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasNext());
      hash = (37 * hash) + HASPREVIOUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasPrevious());
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + getServerTime().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PageResultAssetDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PageResultAssetDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PageResultAssetDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PageResultAssetDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PageResultAssetDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PageResultAssetDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PageResultAssetDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PageResultAssetDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PageResultAssetDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PageResultAssetDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PageResultAssetDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PageResultAssetDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PageResultAssetDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PageResultAssetDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PageResultAssetDTO)
        PageResultAssetDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Asset.internal_static_PageResultAssetDTO_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Asset.internal_static_PageResultAssetDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PageResultAssetDTO.class, Builder.class);
      }

      // Construct using Asset.PageResultAssetDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        pageSize_ = 0;

        totalResults_ = 0L;

        currentPage_ = 0;

        totalPage_ = 0;

        hasNext_ = false;

        hasPrevious_ = false;

        success_ = false;

        code_ = 0;

        message_ = "";

        serverTime_ = "";

        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000400);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Asset.internal_static_PageResultAssetDTO_descriptor;
      }

      public PageResultAssetDTO getDefaultInstanceForType() {
        return PageResultAssetDTO.getDefaultInstance();
      }

      public PageResultAssetDTO build() {
        PageResultAssetDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PageResultAssetDTO buildPartial() {
        PageResultAssetDTO result = new PageResultAssetDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.pageSize_ = pageSize_;
        result.totalResults_ = totalResults_;
        result.currentPage_ = currentPage_;
        result.totalPage_ = totalPage_;
        result.hasNext_ = hasNext_;
        result.hasPrevious_ = hasPrevious_;
        result.success_ = success_;
        result.code_ = code_;
        result.message_ = message_;
        result.serverTime_ = serverTime_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000400) == 0x00000400)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000400);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PageResultAssetDTO) {
          return mergeFrom((PageResultAssetDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PageResultAssetDTO other) {
        if (other == PageResultAssetDTO.getDefaultInstance()) return this;
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        if (other.getTotalResults() != 0L) {
          setTotalResults(other.getTotalResults());
        }
        if (other.getCurrentPage() != 0) {
          setCurrentPage(other.getCurrentPage());
        }
        if (other.getTotalPage() != 0) {
          setTotalPage(other.getTotalPage());
        }
        if (other.getHasNext() != false) {
          setHasNext(other.getHasNext());
        }
        if (other.getHasPrevious() != false) {
          setHasPrevious(other.getHasPrevious());
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getServerTime().isEmpty()) {
          serverTime_ = other.serverTime_;
          onChanged();
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000400);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000400);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PageResultAssetDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PageResultAssetDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int pageSize_ ;
      /**
       * <code>int32 pageSize = 1;</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>int32 pageSize = 1;</code>
       */
      public Builder setPageSize(int value) {
        
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pageSize = 1;</code>
       */
      public Builder clearPageSize() {
        
        pageSize_ = 0;
        onChanged();
        return this;
      }

      private long totalResults_ ;
      /**
       * <code>int64 totalResults = 2;</code>
       */
      public long getTotalResults() {
        return totalResults_;
      }
      /**
       * <code>int64 totalResults = 2;</code>
       */
      public Builder setTotalResults(long value) {
        
        totalResults_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 totalResults = 2;</code>
       */
      public Builder clearTotalResults() {
        
        totalResults_ = 0L;
        onChanged();
        return this;
      }

      private int currentPage_ ;
      /**
       * <code>int32 currentPage = 3;</code>
       */
      public int getCurrentPage() {
        return currentPage_;
      }
      /**
       * <code>int32 currentPage = 3;</code>
       */
      public Builder setCurrentPage(int value) {
        
        currentPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentPage = 3;</code>
       */
      public Builder clearCurrentPage() {
        
        currentPage_ = 0;
        onChanged();
        return this;
      }

      private int totalPage_ ;
      /**
       * <code>int32 totalPage = 4;</code>
       */
      public int getTotalPage() {
        return totalPage_;
      }
      /**
       * <code>int32 totalPage = 4;</code>
       */
      public Builder setTotalPage(int value) {
        
        totalPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalPage = 4;</code>
       */
      public Builder clearTotalPage() {
        
        totalPage_ = 0;
        onChanged();
        return this;
      }

      private boolean hasNext_ ;
      /**
       * <code>bool hasNext = 5;</code>
       */
      public boolean getHasNext() {
        return hasNext_;
      }
      /**
       * <code>bool hasNext = 5;</code>
       */
      public Builder setHasNext(boolean value) {
        
        hasNext_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool hasNext = 5;</code>
       */
      public Builder clearHasNext() {
        
        hasNext_ = false;
        onChanged();
        return this;
      }

      private boolean hasPrevious_ ;
      /**
       * <code>bool hasPrevious = 6;</code>
       */
      public boolean getHasPrevious() {
        return hasPrevious_;
      }
      /**
       * <code>bool hasPrevious = 6;</code>
       */
      public Builder setHasPrevious(boolean value) {
        
        hasPrevious_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool hasPrevious = 6;</code>
       */
      public Builder clearHasPrevious() {
        
        hasPrevious_ = false;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 7;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 7;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 7;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 8;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 8;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 8;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <code>string message = 9;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string message = 9;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 9;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 9;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 9;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private Object serverTime_ = "";
      /**
       * <code>string serverTime = 10;</code>
       */
      public String getServerTime() {
        Object ref = serverTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serverTime = 10;</code>
       */
      public com.google.protobuf.ByteString
          getServerTimeBytes() {
        Object ref = serverTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverTime = 10;</code>
       */
      public Builder setServerTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serverTime = 10;</code>
       */
      public Builder clearServerTime() {
        
        serverTime_ = getDefaultInstance().getServerTime();
        onChanged();
        return this;
      }
      /**
       * <code>string serverTime = 10;</code>
       */
      public Builder setServerTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverTime_ = value;
        onChanged();
        return this;
      }

      private java.util.List<AssetDTO> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000400) == 0x00000400)) {
          data_ = new java.util.ArrayList<AssetDTO>(data_);
          bitField0_ |= 0x00000400;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AssetDTO, AssetDTO.Builder, AssetDTOOrBuilder> dataBuilder_;

      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public java.util.List<AssetDTO> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public AssetDTO getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public Builder setData(
          int index, AssetDTO value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public Builder setData(
          int index, AssetDTO.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public Builder addData(AssetDTO value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public Builder addData(
          int index, AssetDTO value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public Builder addData(
          AssetDTO.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public Builder addData(
          int index, AssetDTO.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public Builder addAllData(
          Iterable<? extends AssetDTO> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000400);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public AssetDTO.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public AssetDTOOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public java.util.List<? extends AssetDTOOrBuilder>
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public AssetDTO.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            AssetDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public AssetDTO.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, AssetDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .AssetDTO data = 11;</code>
       */
      public java.util.List<AssetDTO.Builder>
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AssetDTO, AssetDTO.Builder, AssetDTOOrBuilder>
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AssetDTO, AssetDTO.Builder, AssetDTOOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000400) == 0x00000400),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PageResultAssetDTO)
    }

    // @@protoc_insertion_point(class_scope:PageResultAssetDTO)
    private static final PageResultAssetDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PageResultAssetDTO();
    }

    public static PageResultAssetDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PageResultAssetDTO>
        PARSER = new com.google.protobuf.AbstractParser<PageResultAssetDTO>() {
      public PageResultAssetDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PageResultAssetDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PageResultAssetDTO> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PageResultAssetDTO> getParserForType() {
      return PARSER;
    }

    public PageResultAssetDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AssetDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AssetDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PageResultAssetDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PageResultAssetDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013asset.proto\"\246\001\n\010AssetDTO\022\030\n\020capitalAva" +
      "ilable\030\001 \001(\001\022\026\n\016capitalBalance\030\002 \001(\001\022\025\n\r" +
      "capitalFrozen\030\003 \001(\001\022\021\n\tcapitalId\030\004 \001(\003\022\022" +
      "\n\ncurrencyId\030\005 \001(\003\022\032\n\022currencySimpleName" +
      "\030\006 \001(\t\022\016\n\006userId\030\007 \001(\003\"\347\001\n\022PageResultAss" +
      "etDTO\022\020\n\010pageSize\030\001 \001(\005\022\024\n\014totalResults\030" +
      "\002 \001(\003\022\023\n\013currentPage\030\003 \001(\005\022\021\n\ttotalPage\030" +
      "\004 \001(\005\022\017\n\007hasNext\030\005 \001(\010\022\023\n\013hasPrevious\030\006 " +
      "\001(\010\022\017\n\007success\030\007 \001(\010\022\014\n\004code\030\010 \001(\005\022\017\n\007me" +
      "ssage\030\t \001(\t\022\022\n\nserverTime\030\n \001(\t\022\027\n\004data\030" +
      "\013 \003(\0132\t.AssetDTOb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AssetDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AssetDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AssetDTO_descriptor,
        new String[] { "CapitalAvailable", "CapitalBalance", "CapitalFrozen", "CapitalId", "CurrencyId", "CurrencySimpleName", "UserId", });
    internal_static_PageResultAssetDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PageResultAssetDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PageResultAssetDTO_descriptor,
        new String[] { "PageSize", "TotalResults", "CurrentPage", "TotalPage", "HasNext", "HasPrevious", "Success", "Code", "Message", "ServerTime", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
