package com.happy.otc.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authInfo.proto

public final class AuthInfo {
  private AuthInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code AuthType}
   */
  public enum AuthType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *身份证
     * </pre>
     *
     * <code>ID_CARD = 0;</code>
     */
    ID_CARD(0),
    /**
     * <pre>
     *护照
     * </pre>
     *
     * <code>PASSPORT = 1;</code>
     */
    PASSPORT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *身份证
     * </pre>
     *
     * <code>ID_CARD = 0;</code>
     */
    public static final int ID_CARD_VALUE = 0;
    /**
     * <pre>
     *护照
     * </pre>
     *
     * <code>PASSPORT = 1;</code>
     */
    public static final int PASSPORT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static AuthType valueOf(int value) {
      return forNumber(value);
    }

    public static AuthType forNumber(int value) {
      switch (value) {
        case 0: return ID_CARD;
        case 1: return PASSPORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AuthType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AuthType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AuthType>() {
            public AuthType findValueByNumber(int number) {
              return AuthType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AuthInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final AuthType[] VALUES = values();

    public static AuthType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AuthType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:AuthType)
  }

  /**
   * Protobuf enum {@code AuthStatus}
   */
  public enum AuthStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未认证
     * </pre>
     *
     * <code>NO = 0;</code>
     */
    NO(0),
    /**
     * <pre>
     *待认证
     * </pre>
     *
     * <code>WAITING = 1;</code>
     */
    WAITING(1),
    /**
     * <pre>
     *已认证
     * </pre>
     *
     * <code>YES = 2;</code>
     */
    YES(2),
    /**
     * <pre>
     *认证驳回
     * </pre>
     *
     * <code>REJECT = 3;</code>
     */
    REJECT(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *未认证
     * </pre>
     *
     * <code>NO = 0;</code>
     */
    public static final int NO_VALUE = 0;
    /**
     * <pre>
     *待认证
     * </pre>
     *
     * <code>WAITING = 1;</code>
     */
    public static final int WAITING_VALUE = 1;
    /**
     * <pre>
     *已认证
     * </pre>
     *
     * <code>YES = 2;</code>
     */
    public static final int YES_VALUE = 2;
    /**
     * <pre>
     *认证驳回
     * </pre>
     *
     * <code>REJECT = 3;</code>
     */
    public static final int REJECT_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static AuthStatus valueOf(int value) {
      return forNumber(value);
    }

    public static AuthStatus forNumber(int value) {
      switch (value) {
        case 0: return NO;
        case 1: return WAITING;
        case 2: return YES;
        case 3: return REJECT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AuthStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AuthStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AuthStatus>() {
            public AuthStatus findValueByNumber(int number) {
              return AuthStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AuthInfo.getDescriptor().getEnumTypes().get(1);
    }

    private static final AuthStatus[] VALUES = values();

    public static AuthStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AuthStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:AuthStatus)
  }

  /**
   * Protobuf enum {@code AuthRejectReason}
   */
  public enum AuthRejectReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *无
     * </pre>
     *
     * <code>NULL = 0;</code>
     */
    NULL(0),
    /**
     * <pre>
     *边角不完整
     * </pre>
     *
     * <code>INCOMPLETE = 1;</code>
     */
    INCOMPLETE(1),
    /**
     * <pre>
     *字体不清晰
     * </pre>
     *
     * <code>FONT_ERROR = 2;</code>
     */
    FONT_ERROR(2),
    /**
     * <pre>
     *亮度不均匀
     * </pre>
     *
     * <code>LIGHT_ERROR = 3;</code>
     */
    LIGHT_ERROR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *无
     * </pre>
     *
     * <code>NULL = 0;</code>
     */
    public static final int NULL_VALUE = 0;
    /**
     * <pre>
     *边角不完整
     * </pre>
     *
     * <code>INCOMPLETE = 1;</code>
     */
    public static final int INCOMPLETE_VALUE = 1;
    /**
     * <pre>
     *字体不清晰
     * </pre>
     *
     * <code>FONT_ERROR = 2;</code>
     */
    public static final int FONT_ERROR_VALUE = 2;
    /**
     * <pre>
     *亮度不均匀
     * </pre>
     *
     * <code>LIGHT_ERROR = 3;</code>
     */
    public static final int LIGHT_ERROR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static AuthRejectReason valueOf(int value) {
      return forNumber(value);
    }

    public static AuthRejectReason forNumber(int value) {
      switch (value) {
        case 0: return NULL;
        case 1: return INCOMPLETE;
        case 2: return FONT_ERROR;
        case 3: return LIGHT_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AuthRejectReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AuthRejectReason> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AuthRejectReason>() {
            public AuthRejectReason findValueByNumber(int number) {
              return AuthRejectReason.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AuthInfo.getDescriptor().getEnumTypes().get(2);
    }

    private static final AuthRejectReason[] VALUES = values();

    public static AuthRejectReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AuthRejectReason(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:AuthRejectReason)
  }

  public interface AuthInfoVOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AuthInfoVO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * : 证件类型 0:身份证 1:护照 ,
     * </pre>
     *
     * <code>.AuthType documentType = 1;</code>
     */
    int getDocumentTypeValue();
    /**
     * <pre>
     * : 证件类型 0:身份证 1:护照 ,
     * </pre>
     *
     * <code>.AuthType documentType = 1;</code>
     */
    AuthType getDocumentType();

    /**
     * <pre>
     * 认证编号 ,
     * </pre>
     *
     * <code>int64 id = 2;</code>
     */
    long getId();

    /**
     * <pre>
     * 身份证号码 ,
     * </pre>
     *
     * <code>string identityNumber = 3;</code>
     */
    String getIdentityNumber();
    /**
     * <pre>
     * 身份证号码 ,
     * </pre>
     *
     * <code>string identityNumber = 3;</code>
     */
    com.google.protobuf.ByteString
        getIdentityNumberBytes();

    /**
     * <pre>
     * 图片地址 身份证正面  , 或者护照页
     * </pre>
     *
     * <code>string imageAddress1 = 4;</code>
     */
    String getImageAddress1();
    /**
     * <pre>
     * 图片地址 身份证正面  , 或者护照页
     * </pre>
     *
     * <code>string imageAddress1 = 4;</code>
     */
    com.google.protobuf.ByteString
        getImageAddress1Bytes();

    /**
     * <pre>
     * 图片地址 身份反面  ,
     * </pre>
     *
     * <code>string imageAddress2 = 5;</code>
     */
    String getImageAddress2();
    /**
     * <pre>
     * 图片地址 身份反面  ,
     * </pre>
     *
     * <code>string imageAddress2 = 5;</code>
     */
    com.google.protobuf.ByteString
        getImageAddress2Bytes();

    /**
     * <pre>
     * 身份证、  手持 , ,
     * </pre>
     *
     * <code>string imageAddress3 = 6;</code>
     */
    String getImageAddress3();
    /**
     * <pre>
     * 身份证、  手持 , ,
     * </pre>
     *
     * <code>string imageAddress3 = 6;</code>
     */
    com.google.protobuf.ByteString
        getImageAddress3Bytes();

    /**
     * <pre>
     * 真是姓名
     * </pre>
     *
     * <code>string realName = 7;</code>
     */
    String getRealName();
    /**
     * <pre>
     * 真是姓名
     * </pre>
     *
     * <code>string realName = 7;</code>
     */
    com.google.protobuf.ByteString
        getRealNameBytes();

    /**
     * <pre>
     * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
     * </pre>
     *
     * <code>repeated .AuthRejectReason rejectReason = 8;</code>
     */
    java.util.List<AuthRejectReason> getRejectReasonList();
    /**
     * <pre>
     * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
     * </pre>
     *
     * <code>repeated .AuthRejectReason rejectReason = 8;</code>
     */
    int getRejectReasonCount();
    /**
     * <pre>
     * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
     * </pre>
     *
     * <code>repeated .AuthRejectReason rejectReason = 8;</code>
     */
    AuthRejectReason getRejectReason(int index);
    /**
     * <pre>
     * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
     * </pre>
     *
     * <code>repeated .AuthRejectReason rejectReason = 8;</code>
     */
    java.util.List<Integer>
    getRejectReasonValueList();
    /**
     * <pre>
     * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
     * </pre>
     *
     * <code>repeated .AuthRejectReason rejectReason = 8;</code>
     */
    int getRejectReasonValue(int index);

    /**
     * <pre>
     * 认证状态  0:未认证 1:待认证 2:已认证 3:认证驳回
     * </pre>
     *
     * <code>.AuthStatus status = 9;</code>
     */
    int getStatusValue();
    /**
     * <pre>
     * 认证状态  0:未认证 1:待认证 2:已认证 3:认证驳回
     * </pre>
     *
     * <code>.AuthStatus status = 9;</code>
     */
    AuthStatus getStatus();

    /**
     * <code>int32 userId = 10;</code>
     */
    int getUserId();

    /**
     * <pre>
     *其他驳回理由
     * </pre>
     *
     * <code>string otherReason = 11;</code>
     */
    String getOtherReason();
    /**
     * <pre>
     *其他驳回理由
     * </pre>
     *
     * <code>string otherReason = 11;</code>
     */
    com.google.protobuf.ByteString
        getOtherReasonBytes();
  }
  /**
   * Protobuf type {@code AuthInfoVO}
   */
  public  static final class AuthInfoVO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AuthInfoVO)
      AuthInfoVOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthInfoVO.newBuilder() to construct.
    private AuthInfoVO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthInfoVO() {
      documentType_ = 0;
      id_ = 0L;
      identityNumber_ = "";
      imageAddress1_ = "";
      imageAddress2_ = "";
      imageAddress3_ = "";
      realName_ = "";
      rejectReason_ = java.util.Collections.emptyList();
      status_ = 0;
      userId_ = 0;
      otherReason_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthInfoVO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              documentType_ = rawValue;
              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              identityNumber_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              imageAddress1_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              imageAddress2_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              imageAddress3_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              realName_ = s;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                rejectReason_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000080;
              }
              rejectReason_.add(rawValue);
              break;
            }
            case 66: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                  rejectReason_ = new java.util.ArrayList<Integer>();
                  mutable_bitField0_ |= 0x00000080;
                }
                rejectReason_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
            case 72: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 80: {

              userId_ = input.readInt32();
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              otherReason_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          rejectReason_ = java.util.Collections.unmodifiableList(rejectReason_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AuthInfo.internal_static_AuthInfoVO_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AuthInfo.internal_static_AuthInfoVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AuthInfoVO.class, Builder.class);
    }

    private int bitField0_;
    public static final int DOCUMENTTYPE_FIELD_NUMBER = 1;
    private int documentType_;
    /**
     * <pre>
     * : 证件类型 0:身份证 1:护照 ,
     * </pre>
     *
     * <code>.AuthType documentType = 1;</code>
     */
    public int getDocumentTypeValue() {
      return documentType_;
    }
    /**
     * <pre>
     * : 证件类型 0:身份证 1:护照 ,
     * </pre>
     *
     * <code>.AuthType documentType = 1;</code>
     */
    public AuthType getDocumentType() {
      AuthType result = AuthType.valueOf(documentType_);
      return result == null ? AuthType.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <pre>
     * 认证编号 ,
     * </pre>
     *
     * <code>int64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int IDENTITYNUMBER_FIELD_NUMBER = 3;
    private volatile Object identityNumber_;
    /**
     * <pre>
     * 身份证号码 ,
     * </pre>
     *
     * <code>string identityNumber = 3;</code>
     */
    public String getIdentityNumber() {
      Object ref = identityNumber_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        identityNumber_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 身份证号码 ,
     * </pre>
     *
     * <code>string identityNumber = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIdentityNumberBytes() {
      Object ref = identityNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        identityNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGEADDRESS1_FIELD_NUMBER = 4;
    private volatile Object imageAddress1_;
    /**
     * <pre>
     * 图片地址 身份证正面  , 或者护照页
     * </pre>
     *
     * <code>string imageAddress1 = 4;</code>
     */
    public String getImageAddress1() {
      Object ref = imageAddress1_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imageAddress1_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 图片地址 身份证正面  , 或者护照页
     * </pre>
     *
     * <code>string imageAddress1 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImageAddress1Bytes() {
      Object ref = imageAddress1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imageAddress1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGEADDRESS2_FIELD_NUMBER = 5;
    private volatile Object imageAddress2_;
    /**
     * <pre>
     * 图片地址 身份反面  ,
     * </pre>
     *
     * <code>string imageAddress2 = 5;</code>
     */
    public String getImageAddress2() {
      Object ref = imageAddress2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imageAddress2_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 图片地址 身份反面  ,
     * </pre>
     *
     * <code>string imageAddress2 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getImageAddress2Bytes() {
      Object ref = imageAddress2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imageAddress2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGEADDRESS3_FIELD_NUMBER = 6;
    private volatile Object imageAddress3_;
    /**
     * <pre>
     * 身份证、  手持 , ,
     * </pre>
     *
     * <code>string imageAddress3 = 6;</code>
     */
    public String getImageAddress3() {
      Object ref = imageAddress3_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imageAddress3_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 身份证、  手持 , ,
     * </pre>
     *
     * <code>string imageAddress3 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getImageAddress3Bytes() {
      Object ref = imageAddress3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imageAddress3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REALNAME_FIELD_NUMBER = 7;
    private volatile Object realName_;
    /**
     * <pre>
     * 真是姓名
     * </pre>
     *
     * <code>string realName = 7;</code>
     */
    public String getRealName() {
      Object ref = realName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        realName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 真是姓名
     * </pre>
     *
     * <code>string realName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRealNameBytes() {
      Object ref = realName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        realName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REJECTREASON_FIELD_NUMBER = 8;
    private java.util.List<Integer> rejectReason_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        Integer, AuthRejectReason> rejectReason_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                Integer, AuthRejectReason>() {
              public AuthRejectReason convert(Integer from) {
                AuthRejectReason result = AuthRejectReason.valueOf(from);
                return result == null ? AuthRejectReason.UNRECOGNIZED : result;
              }
            };
    /**
     * <pre>
     * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
     * </pre>
     *
     * <code>repeated .AuthRejectReason rejectReason = 8;</code>
     */
    public java.util.List<AuthRejectReason> getRejectReasonList() {
      return new com.google.protobuf.Internal.ListAdapter<
          Integer, AuthRejectReason>(rejectReason_, rejectReason_converter_);
    }
    /**
     * <pre>
     * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
     * </pre>
     *
     * <code>repeated .AuthRejectReason rejectReason = 8;</code>
     */
    public int getRejectReasonCount() {
      return rejectReason_.size();
    }
    /**
     * <pre>
     * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
     * </pre>
     *
     * <code>repeated .AuthRejectReason rejectReason = 8;</code>
     */
    public AuthRejectReason getRejectReason(int index) {
      return rejectReason_converter_.convert(rejectReason_.get(index));
    }
    /**
     * <pre>
     * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
     * </pre>
     *
     * <code>repeated .AuthRejectReason rejectReason = 8;</code>
     */
    public java.util.List<Integer>
    getRejectReasonValueList() {
      return rejectReason_;
    }
    /**
     * <pre>
     * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
     * </pre>
     *
     * <code>repeated .AuthRejectReason rejectReason = 8;</code>
     */
    public int getRejectReasonValue(int index) {
      return rejectReason_.get(index);
    }
    private int rejectReasonMemoizedSerializedSize;

    public static final int STATUS_FIELD_NUMBER = 9;
    private int status_;
    /**
     * <pre>
     * 认证状态  0:未认证 1:待认证 2:已认证 3:认证驳回
     * </pre>
     *
     * <code>.AuthStatus status = 9;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * 认证状态  0:未认证 1:待认证 2:已认证 3:认证驳回
     * </pre>
     *
     * <code>.AuthStatus status = 9;</code>
     */
    public AuthStatus getStatus() {
      AuthStatus result = AuthStatus.valueOf(status_);
      return result == null ? AuthStatus.UNRECOGNIZED : result;
    }

    public static final int USERID_FIELD_NUMBER = 10;
    private int userId_;
    /**
     * <code>int32 userId = 10;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int OTHERREASON_FIELD_NUMBER = 11;
    private volatile Object otherReason_;
    /**
     * <pre>
     *其他驳回理由
     * </pre>
     *
     * <code>string otherReason = 11;</code>
     */
    public String getOtherReason() {
      Object ref = otherReason_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        otherReason_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *其他驳回理由
     * </pre>
     *
     * <code>string otherReason = 11;</code>
     */
    public com.google.protobuf.ByteString
        getOtherReasonBytes() {
      Object ref = otherReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        otherReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (documentType_ != AuthType.ID_CARD.getNumber()) {
        output.writeEnum(1, documentType_);
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (!getIdentityNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, identityNumber_);
      }
      if (!getImageAddress1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, imageAddress1_);
      }
      if (!getImageAddress2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, imageAddress2_);
      }
      if (!getImageAddress3Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, imageAddress3_);
      }
      if (!getRealNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, realName_);
      }
      if (getRejectReasonList().size() > 0) {
        output.writeUInt32NoTag(66);
        output.writeUInt32NoTag(rejectReasonMemoizedSerializedSize);
      }
      for (int i = 0; i < rejectReason_.size(); i++) {
        output.writeEnumNoTag(rejectReason_.get(i));
      }
      if (status_ != AuthStatus.NO.getNumber()) {
        output.writeEnum(9, status_);
      }
      if (userId_ != 0) {
        output.writeInt32(10, userId_);
      }
      if (!getOtherReasonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, otherReason_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (documentType_ != AuthType.ID_CARD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, documentType_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (!getIdentityNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, identityNumber_);
      }
      if (!getImageAddress1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, imageAddress1_);
      }
      if (!getImageAddress2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, imageAddress2_);
      }
      if (!getImageAddress3Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, imageAddress3_);
      }
      if (!getRealNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, realName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < rejectReason_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(rejectReason_.get(i));
        }
        size += dataSize;
        if (!getRejectReasonList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }rejectReasonMemoizedSerializedSize = dataSize;
      }
      if (status_ != AuthStatus.NO.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, status_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, userId_);
      }
      if (!getOtherReasonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, otherReason_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AuthInfoVO)) {
        return super.equals(obj);
      }
      AuthInfoVO other = (AuthInfoVO) obj;

      boolean result = true;
      result = result && documentType_ == other.documentType_;
      result = result && (getId()
          == other.getId());
      result = result && getIdentityNumber()
          .equals(other.getIdentityNumber());
      result = result && getImageAddress1()
          .equals(other.getImageAddress1());
      result = result && getImageAddress2()
          .equals(other.getImageAddress2());
      result = result && getImageAddress3()
          .equals(other.getImageAddress3());
      result = result && getRealName()
          .equals(other.getRealName());
      result = result && rejectReason_.equals(other.rejectReason_);
      result = result && status_ == other.status_;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getOtherReason()
          .equals(other.getOtherReason());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DOCUMENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + documentType_;
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + IDENTITYNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentityNumber().hashCode();
      hash = (37 * hash) + IMAGEADDRESS1_FIELD_NUMBER;
      hash = (53 * hash) + getImageAddress1().hashCode();
      hash = (37 * hash) + IMAGEADDRESS2_FIELD_NUMBER;
      hash = (53 * hash) + getImageAddress2().hashCode();
      hash = (37 * hash) + IMAGEADDRESS3_FIELD_NUMBER;
      hash = (53 * hash) + getImageAddress3().hashCode();
      hash = (37 * hash) + REALNAME_FIELD_NUMBER;
      hash = (53 * hash) + getRealName().hashCode();
      if (getRejectReasonCount() > 0) {
        hash = (37 * hash) + REJECTREASON_FIELD_NUMBER;
        hash = (53 * hash) + rejectReason_.hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + OTHERREASON_FIELD_NUMBER;
      hash = (53 * hash) + getOtherReason().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AuthInfoVO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AuthInfoVO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AuthInfoVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AuthInfoVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AuthInfoVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AuthInfoVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AuthInfoVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AuthInfoVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AuthInfoVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AuthInfoVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AuthInfoVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AuthInfoVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AuthInfoVO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AuthInfoVO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AuthInfoVO)
        AuthInfoVOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AuthInfo.internal_static_AuthInfoVO_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AuthInfo.internal_static_AuthInfoVO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AuthInfoVO.class, Builder.class);
      }

      // Construct using AuthInfo.AuthInfoVO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        documentType_ = 0;

        id_ = 0L;

        identityNumber_ = "";

        imageAddress1_ = "";

        imageAddress2_ = "";

        imageAddress3_ = "";

        realName_ = "";

        rejectReason_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        status_ = 0;

        userId_ = 0;

        otherReason_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AuthInfo.internal_static_AuthInfoVO_descriptor;
      }

      public AuthInfoVO getDefaultInstanceForType() {
        return AuthInfoVO.getDefaultInstance();
      }

      public AuthInfoVO build() {
        AuthInfoVO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AuthInfoVO buildPartial() {
        AuthInfoVO result = new AuthInfoVO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.documentType_ = documentType_;
        result.id_ = id_;
        result.identityNumber_ = identityNumber_;
        result.imageAddress1_ = imageAddress1_;
        result.imageAddress2_ = imageAddress2_;
        result.imageAddress3_ = imageAddress3_;
        result.realName_ = realName_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          rejectReason_ = java.util.Collections.unmodifiableList(rejectReason_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.rejectReason_ = rejectReason_;
        result.status_ = status_;
        result.userId_ = userId_;
        result.otherReason_ = otherReason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AuthInfoVO) {
          return mergeFrom((AuthInfoVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AuthInfoVO other) {
        if (other == AuthInfoVO.getDefaultInstance()) return this;
        if (other.documentType_ != 0) {
          setDocumentTypeValue(other.getDocumentTypeValue());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getIdentityNumber().isEmpty()) {
          identityNumber_ = other.identityNumber_;
          onChanged();
        }
        if (!other.getImageAddress1().isEmpty()) {
          imageAddress1_ = other.imageAddress1_;
          onChanged();
        }
        if (!other.getImageAddress2().isEmpty()) {
          imageAddress2_ = other.imageAddress2_;
          onChanged();
        }
        if (!other.getImageAddress3().isEmpty()) {
          imageAddress3_ = other.imageAddress3_;
          onChanged();
        }
        if (!other.getRealName().isEmpty()) {
          realName_ = other.realName_;
          onChanged();
        }
        if (!other.rejectReason_.isEmpty()) {
          if (rejectReason_.isEmpty()) {
            rejectReason_ = other.rejectReason_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureRejectReasonIsMutable();
            rejectReason_.addAll(other.rejectReason_);
          }
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getOtherReason().isEmpty()) {
          otherReason_ = other.otherReason_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AuthInfoVO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AuthInfoVO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int documentType_ = 0;
      /**
       * <pre>
       * : 证件类型 0:身份证 1:护照 ,
       * </pre>
       *
       * <code>.AuthType documentType = 1;</code>
       */
      public int getDocumentTypeValue() {
        return documentType_;
      }
      /**
       * <pre>
       * : 证件类型 0:身份证 1:护照 ,
       * </pre>
       *
       * <code>.AuthType documentType = 1;</code>
       */
      public Builder setDocumentTypeValue(int value) {
        documentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * : 证件类型 0:身份证 1:护照 ,
       * </pre>
       *
       * <code>.AuthType documentType = 1;</code>
       */
      public AuthType getDocumentType() {
        AuthType result = AuthType.valueOf(documentType_);
        return result == null ? AuthType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * : 证件类型 0:身份证 1:护照 ,
       * </pre>
       *
       * <code>.AuthType documentType = 1;</code>
       */
      public Builder setDocumentType(AuthType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        documentType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * : 证件类型 0:身份证 1:护照 ,
       * </pre>
       *
       * <code>.AuthType documentType = 1;</code>
       */
      public Builder clearDocumentType() {
        
        documentType_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       * 认证编号 ,
       * </pre>
       *
       * <code>int64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * 认证编号 ,
       * </pre>
       *
       * <code>int64 id = 2;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 认证编号 ,
       * </pre>
       *
       * <code>int64 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private Object identityNumber_ = "";
      /**
       * <pre>
       * 身份证号码 ,
       * </pre>
       *
       * <code>string identityNumber = 3;</code>
       */
      public String getIdentityNumber() {
        Object ref = identityNumber_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          identityNumber_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 身份证号码 ,
       * </pre>
       *
       * <code>string identityNumber = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIdentityNumberBytes() {
        Object ref = identityNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          identityNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 身份证号码 ,
       * </pre>
       *
       * <code>string identityNumber = 3;</code>
       */
      public Builder setIdentityNumber(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identityNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 身份证号码 ,
       * </pre>
       *
       * <code>string identityNumber = 3;</code>
       */
      public Builder clearIdentityNumber() {
        
        identityNumber_ = getDefaultInstance().getIdentityNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 身份证号码 ,
       * </pre>
       *
       * <code>string identityNumber = 3;</code>
       */
      public Builder setIdentityNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        identityNumber_ = value;
        onChanged();
        return this;
      }

      private Object imageAddress1_ = "";
      /**
       * <pre>
       * 图片地址 身份证正面  , 或者护照页
       * </pre>
       *
       * <code>string imageAddress1 = 4;</code>
       */
      public String getImageAddress1() {
        Object ref = imageAddress1_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          imageAddress1_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 图片地址 身份证正面  , 或者护照页
       * </pre>
       *
       * <code>string imageAddress1 = 4;</code>
       */
      public com.google.protobuf.ByteString
          getImageAddress1Bytes() {
        Object ref = imageAddress1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          imageAddress1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 图片地址 身份证正面  , 或者护照页
       * </pre>
       *
       * <code>string imageAddress1 = 4;</code>
       */
      public Builder setImageAddress1(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageAddress1_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 图片地址 身份证正面  , 或者护照页
       * </pre>
       *
       * <code>string imageAddress1 = 4;</code>
       */
      public Builder clearImageAddress1() {
        
        imageAddress1_ = getDefaultInstance().getImageAddress1();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 图片地址 身份证正面  , 或者护照页
       * </pre>
       *
       * <code>string imageAddress1 = 4;</code>
       */
      public Builder setImageAddress1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageAddress1_ = value;
        onChanged();
        return this;
      }

      private Object imageAddress2_ = "";
      /**
       * <pre>
       * 图片地址 身份反面  ,
       * </pre>
       *
       * <code>string imageAddress2 = 5;</code>
       */
      public String getImageAddress2() {
        Object ref = imageAddress2_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          imageAddress2_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 图片地址 身份反面  ,
       * </pre>
       *
       * <code>string imageAddress2 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getImageAddress2Bytes() {
        Object ref = imageAddress2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          imageAddress2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 图片地址 身份反面  ,
       * </pre>
       *
       * <code>string imageAddress2 = 5;</code>
       */
      public Builder setImageAddress2(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageAddress2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 图片地址 身份反面  ,
       * </pre>
       *
       * <code>string imageAddress2 = 5;</code>
       */
      public Builder clearImageAddress2() {
        
        imageAddress2_ = getDefaultInstance().getImageAddress2();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 图片地址 身份反面  ,
       * </pre>
       *
       * <code>string imageAddress2 = 5;</code>
       */
      public Builder setImageAddress2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageAddress2_ = value;
        onChanged();
        return this;
      }

      private Object imageAddress3_ = "";
      /**
       * <pre>
       * 身份证、  手持 , ,
       * </pre>
       *
       * <code>string imageAddress3 = 6;</code>
       */
      public String getImageAddress3() {
        Object ref = imageAddress3_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          imageAddress3_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 身份证、  手持 , ,
       * </pre>
       *
       * <code>string imageAddress3 = 6;</code>
       */
      public com.google.protobuf.ByteString
          getImageAddress3Bytes() {
        Object ref = imageAddress3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          imageAddress3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 身份证、  手持 , ,
       * </pre>
       *
       * <code>string imageAddress3 = 6;</code>
       */
      public Builder setImageAddress3(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageAddress3_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 身份证、  手持 , ,
       * </pre>
       *
       * <code>string imageAddress3 = 6;</code>
       */
      public Builder clearImageAddress3() {
        
        imageAddress3_ = getDefaultInstance().getImageAddress3();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 身份证、  手持 , ,
       * </pre>
       *
       * <code>string imageAddress3 = 6;</code>
       */
      public Builder setImageAddress3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageAddress3_ = value;
        onChanged();
        return this;
      }

      private Object realName_ = "";
      /**
       * <pre>
       * 真是姓名
       * </pre>
       *
       * <code>string realName = 7;</code>
       */
      public String getRealName() {
        Object ref = realName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          realName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 真是姓名
       * </pre>
       *
       * <code>string realName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getRealNameBytes() {
        Object ref = realName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          realName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 真是姓名
       * </pre>
       *
       * <code>string realName = 7;</code>
       */
      public Builder setRealName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        realName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 真是姓名
       * </pre>
       *
       * <code>string realName = 7;</code>
       */
      public Builder clearRealName() {
        
        realName_ = getDefaultInstance().getRealName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 真是姓名
       * </pre>
       *
       * <code>string realName = 7;</code>
       */
      public Builder setRealNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        realName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Integer> rejectReason_ =
        java.util.Collections.emptyList();
      private void ensureRejectReasonIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          rejectReason_ = new java.util.ArrayList<Integer>(rejectReason_);
          bitField0_ |= 0x00000080;
        }
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public java.util.List<AuthRejectReason> getRejectReasonList() {
        return new com.google.protobuf.Internal.ListAdapter<
            Integer, AuthRejectReason>(rejectReason_, rejectReason_converter_);
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public int getRejectReasonCount() {
        return rejectReason_.size();
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public AuthRejectReason getRejectReason(int index) {
        return rejectReason_converter_.convert(rejectReason_.get(index));
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public Builder setRejectReason(
          int index, AuthRejectReason value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRejectReasonIsMutable();
        rejectReason_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public Builder addRejectReason(AuthRejectReason value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRejectReasonIsMutable();
        rejectReason_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public Builder addAllRejectReason(
          Iterable<? extends AuthRejectReason> values) {
        ensureRejectReasonIsMutable();
        for (AuthRejectReason value : values) {
          rejectReason_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public Builder clearRejectReason() {
        rejectReason_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public java.util.List<Integer>
      getRejectReasonValueList() {
        return java.util.Collections.unmodifiableList(rejectReason_);
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public int getRejectReasonValue(int index) {
        return rejectReason_.get(index);
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public Builder setRejectReasonValue(
          int index, int value) {
        ensureRejectReasonIsMutable();
        rejectReason_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public Builder addRejectReasonValue(int value) {
        ensureRejectReasonIsMutable();
        rejectReason_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 驳回理由 0:无 1:边角不完整 2:字体不清晰 3:亮度不均匀
       * </pre>
       *
       * <code>repeated .AuthRejectReason rejectReason = 8;</code>
       */
      public Builder addAllRejectReasonValue(
          Iterable<Integer> values) {
        ensureRejectReasonIsMutable();
        for (int value : values) {
          rejectReason_.add(value);
        }
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <pre>
       * 认证状态  0:未认证 1:待认证 2:已认证 3:认证驳回
       * </pre>
       *
       * <code>.AuthStatus status = 9;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <pre>
       * 认证状态  0:未认证 1:待认证 2:已认证 3:认证驳回
       * </pre>
       *
       * <code>.AuthStatus status = 9;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 认证状态  0:未认证 1:待认证 2:已认证 3:认证驳回
       * </pre>
       *
       * <code>.AuthStatus status = 9;</code>
       */
      public AuthStatus getStatus() {
        AuthStatus result = AuthStatus.valueOf(status_);
        return result == null ? AuthStatus.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 认证状态  0:未认证 1:待认证 2:已认证 3:认证驳回
       * </pre>
       *
       * <code>.AuthStatus status = 9;</code>
       */
      public Builder setStatus(AuthStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 认证状态  0:未认证 1:待认证 2:已认证 3:认证驳回
       * </pre>
       *
       * <code>.AuthStatus status = 9;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 userId = 10;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 10;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 10;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private Object otherReason_ = "";
      /**
       * <pre>
       *其他驳回理由
       * </pre>
       *
       * <code>string otherReason = 11;</code>
       */
      public String getOtherReason() {
        Object ref = otherReason_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          otherReason_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *其他驳回理由
       * </pre>
       *
       * <code>string otherReason = 11;</code>
       */
      public com.google.protobuf.ByteString
          getOtherReasonBytes() {
        Object ref = otherReason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          otherReason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *其他驳回理由
       * </pre>
       *
       * <code>string otherReason = 11;</code>
       */
      public Builder setOtherReason(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        otherReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他驳回理由
       * </pre>
       *
       * <code>string otherReason = 11;</code>
       */
      public Builder clearOtherReason() {
        
        otherReason_ = getDefaultInstance().getOtherReason();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他驳回理由
       * </pre>
       *
       * <code>string otherReason = 11;</code>
       */
      public Builder setOtherReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        otherReason_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AuthInfoVO)
    }

    // @@protoc_insertion_point(class_scope:AuthInfoVO)
    private static final AuthInfoVO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AuthInfoVO();
    }

    public static AuthInfoVO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthInfoVO>
        PARSER = new com.google.protobuf.AbstractParser<AuthInfoVO>() {
      public AuthInfoVO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthInfoVO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthInfoVO> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AuthInfoVO> getParserForType() {
      return PARSER;
    }

    public AuthInfoVO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthInfoVO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthInfoVO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016authInfo.proto\"\223\002\n\nAuthInfoVO\022\037\n\014docum" +
      "entType\030\001 \001(\0162\t.AuthType\022\n\n\002id\030\002 \001(\003\022\026\n\016" +
      "identityNumber\030\003 \001(\t\022\025\n\rimageAddress1\030\004 " +
      "\001(\t\022\025\n\rimageAddress2\030\005 \001(\t\022\025\n\rimageAddre" +
      "ss3\030\006 \001(\t\022\020\n\010realName\030\007 \001(\t\022\'\n\014rejectRea" +
      "son\030\010 \003(\0162\021.AuthRejectReason\022\033\n\006status\030\t" +
      " \001(\0162\013.AuthStatus\022\016\n\006userId\030\n \001(\005\022\023\n\013oth" +
      "erReason\030\013 \001(\t*%\n\010AuthType\022\013\n\007ID_CARD\020\000\022" +
      "\014\n\010PASSPORT\020\001*6\n\nAuthStatus\022\006\n\002NO\020\000\022\013\n\007W" +
      "AITING\020\001\022\007\n\003YES\020\002\022\n\n\006REJECT\020\003*M\n\020AuthRej" +
      "ectReason\022\010\n\004NULL\020\000\022\016\n\nINCOMPLETE\020\001\022\016\n\nF" +
      "ONT_ERROR\020\002\022\017\n\013LIGHT_ERROR\020\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AuthInfoVO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AuthInfoVO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthInfoVO_descriptor,
        new String[] { "DocumentType", "Id", "IdentityNumber", "ImageAddress1", "ImageAddress2", "ImageAddress3", "RealName", "RejectReason", "Status", "UserId", "OtherReason", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
