package com.happy.otc.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blackListInfo.proto

public final class BlackListInfo {
  private BlackListInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlackListInfoVOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BlackListInfoVO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *黑名单id
     * </pre>
     *
     * <code>int64 blackListId = 1;</code>
     */
    long getBlackListId();

    /**
     * <pre>
     *屏蔽人id
     * </pre>
     *
     * <code>int64 userId = 2;</code>
     */
    long getUserId();

    /**
     * <pre>
     *被屏蔽人id
     * </pre>
     *
     * <code>int64 targetId = 3;</code>
     */
    long getTargetId();

    /**
     * <pre>
     *被屏蔽人名称
     * </pre>
     *
     * <code>string targetName = 4;</code>
     */
    String getTargetName();
    /**
     * <pre>
     *被屏蔽人名称
     * </pre>
     *
     * <code>string targetName = 4;</code>
     */
    com.google.protobuf.ByteString
        getTargetNameBytes();

    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 createTime = 5;</code>
     */
    long getCreateTime();
  }
  /**
   * Protobuf type {@code BlackListInfoVO}
   */
  public  static final class BlackListInfoVO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BlackListInfoVO)
      BlackListInfoVOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BlackListInfoVO.newBuilder() to construct.
    private BlackListInfoVO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlackListInfoVO() {
      blackListId_ = 0L;
      userId_ = 0L;
      targetId_ = 0L;
      targetName_ = "";
      createTime_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlackListInfoVO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              blackListId_ = input.readInt64();
              break;
            }
            case 16: {

              userId_ = input.readInt64();
              break;
            }
            case 24: {

              targetId_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              targetName_ = s;
              break;
            }
            case 40: {

              createTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BlackListInfo.internal_static_BlackListInfoVO_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BlackListInfo.internal_static_BlackListInfoVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BlackListInfo.BlackListInfoVO.class, BlackListInfo.BlackListInfoVO.Builder.class);
    }

    public static final int BLACKLISTID_FIELD_NUMBER = 1;
    private long blackListId_;
    /**
     * <pre>
     *黑名单id
     * </pre>
     *
     * <code>int64 blackListId = 1;</code>
     */
    public long getBlackListId() {
      return blackListId_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <pre>
     *屏蔽人id
     * </pre>
     *
     * <code>int64 userId = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int TARGETID_FIELD_NUMBER = 3;
    private long targetId_;
    /**
     * <pre>
     *被屏蔽人id
     * </pre>
     *
     * <code>int64 targetId = 3;</code>
     */
    public long getTargetId() {
      return targetId_;
    }

    public static final int TARGETNAME_FIELD_NUMBER = 4;
    private volatile Object targetName_;
    /**
     * <pre>
     *被屏蔽人名称
     * </pre>
     *
     * <code>string targetName = 4;</code>
     */
    public String getTargetName() {
      Object ref = targetName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        targetName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *被屏蔽人名称
     * </pre>
     *
     * <code>string targetName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTargetNameBytes() {
      Object ref = targetName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        targetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 5;
    private long createTime_;
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>int64 createTime = 5;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (blackListId_ != 0L) {
        output.writeInt64(1, blackListId_);
      }
      if (userId_ != 0L) {
        output.writeInt64(2, userId_);
      }
      if (targetId_ != 0L) {
        output.writeInt64(3, targetId_);
      }
      if (!getTargetNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, targetName_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(5, createTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (blackListId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, blackListId_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (targetId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, targetId_);
      }
      if (!getTargetNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, targetName_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, createTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BlackListInfo.BlackListInfoVO)) {
        return super.equals(obj);
      }
      BlackListInfo.BlackListInfoVO other = (BlackListInfo.BlackListInfoVO) obj;

      boolean result = true;
      result = result && (getBlackListId()
          == other.getBlackListId());
      result = result && (getUserId()
          == other.getUserId());
      result = result && (getTargetId()
          == other.getTargetId());
      result = result && getTargetName()
          .equals(other.getTargetName());
      result = result && (getCreateTime()
          == other.getCreateTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLACKLISTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlackListId());
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + TARGETID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTargetId());
      hash = (37 * hash) + TARGETNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTargetName().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BlackListInfo.BlackListInfoVO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlackListInfo.BlackListInfoVO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlackListInfo.BlackListInfoVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlackListInfo.BlackListInfoVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlackListInfo.BlackListInfoVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlackListInfo.BlackListInfoVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlackListInfo.BlackListInfoVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BlackListInfo.BlackListInfoVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BlackListInfo.BlackListInfoVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BlackListInfo.BlackListInfoVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BlackListInfo.BlackListInfoVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BlackListInfo.BlackListInfoVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BlackListInfo.BlackListInfoVO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BlackListInfoVO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BlackListInfoVO)
        BlackListInfo.BlackListInfoVOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BlackListInfo.internal_static_BlackListInfoVO_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BlackListInfo.internal_static_BlackListInfoVO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BlackListInfo.BlackListInfoVO.class, BlackListInfo.BlackListInfoVO.Builder.class);
      }

      // Construct using BlackListInfo.BlackListInfoVO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        blackListId_ = 0L;

        userId_ = 0L;

        targetId_ = 0L;

        targetName_ = "";

        createTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BlackListInfo.internal_static_BlackListInfoVO_descriptor;
      }

      public BlackListInfo.BlackListInfoVO getDefaultInstanceForType() {
        return BlackListInfo.BlackListInfoVO.getDefaultInstance();
      }

      public BlackListInfo.BlackListInfoVO build() {
        BlackListInfo.BlackListInfoVO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BlackListInfo.BlackListInfoVO buildPartial() {
        BlackListInfo.BlackListInfoVO result = new BlackListInfo.BlackListInfoVO(this);
        result.blackListId_ = blackListId_;
        result.userId_ = userId_;
        result.targetId_ = targetId_;
        result.targetName_ = targetName_;
        result.createTime_ = createTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BlackListInfo.BlackListInfoVO) {
          return mergeFrom((BlackListInfo.BlackListInfoVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BlackListInfo.BlackListInfoVO other) {
        if (other == BlackListInfo.BlackListInfoVO.getDefaultInstance()) return this;
        if (other.getBlackListId() != 0L) {
          setBlackListId(other.getBlackListId());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getTargetId() != 0L) {
          setTargetId(other.getTargetId());
        }
        if (!other.getTargetName().isEmpty()) {
          targetName_ = other.targetName_;
          onChanged();
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BlackListInfo.BlackListInfoVO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BlackListInfo.BlackListInfoVO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long blackListId_ ;
      /**
       * <pre>
       *黑名单id
       * </pre>
       *
       * <code>int64 blackListId = 1;</code>
       */
      public long getBlackListId() {
        return blackListId_;
      }
      /**
       * <pre>
       *黑名单id
       * </pre>
       *
       * <code>int64 blackListId = 1;</code>
       */
      public Builder setBlackListId(long value) {

        blackListId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *黑名单id
       * </pre>
       *
       * <code>int64 blackListId = 1;</code>
       */
      public Builder clearBlackListId() {

        blackListId_ = 0L;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <pre>
       *屏蔽人id
       * </pre>
       *
       * <code>int64 userId = 2;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <pre>
       *屏蔽人id
       * </pre>
       *
       * <code>int64 userId = 2;</code>
       */
      public Builder setUserId(long value) {

        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *屏蔽人id
       * </pre>
       *
       * <code>int64 userId = 2;</code>
       */
      public Builder clearUserId() {

        userId_ = 0L;
        onChanged();
        return this;
      }

      private long targetId_ ;
      /**
       * <pre>
       *被屏蔽人id
       * </pre>
       *
       * <code>int64 targetId = 3;</code>
       */
      public long getTargetId() {
        return targetId_;
      }
      /**
       * <pre>
       *被屏蔽人id
       * </pre>
       *
       * <code>int64 targetId = 3;</code>
       */
      public Builder setTargetId(long value) {

        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *被屏蔽人id
       * </pre>
       *
       * <code>int64 targetId = 3;</code>
       */
      public Builder clearTargetId() {

        targetId_ = 0L;
        onChanged();
        return this;
      }

      private Object targetName_ = "";
      /**
       * <pre>
       *被屏蔽人名称
       * </pre>
       *
       * <code>string targetName = 4;</code>
       */
      public String getTargetName() {
        Object ref = targetName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          targetName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *被屏蔽人名称
       * </pre>
       *
       * <code>string targetName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTargetNameBytes() {
        Object ref = targetName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          targetName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *被屏蔽人名称
       * </pre>
       *
       * <code>string targetName = 4;</code>
       */
      public Builder setTargetName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        targetName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *被屏蔽人名称
       * </pre>
       *
       * <code>string targetName = 4;</code>
       */
      public Builder clearTargetName() {

        targetName_ = getDefaultInstance().getTargetName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *被屏蔽人名称
       * </pre>
       *
       * <code>string targetName = 4;</code>
       */
      public Builder setTargetNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        targetName_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>int64 createTime = 5;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>int64 createTime = 5;</code>
       */
      public Builder setCreateTime(long value) {

        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>int64 createTime = 5;</code>
       */
      public Builder clearCreateTime() {

        createTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BlackListInfoVO)
    }

    // @@protoc_insertion_point(class_scope:BlackListInfoVO)
    private static final BlackListInfo.BlackListInfoVO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BlackListInfo.BlackListInfoVO();
    }

    public static BlackListInfo.BlackListInfoVO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlackListInfoVO>
        PARSER = new com.google.protobuf.AbstractParser<BlackListInfoVO>() {
      public BlackListInfoVO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BlackListInfoVO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlackListInfoVO> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BlackListInfoVO> getParserForType() {
      return PARSER;
    }

    public BlackListInfo.BlackListInfoVO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BlackListInfoVO_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BlackListInfoVO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023blackListInfo.proto\"p\n\017BlackListInfoVO" +
      "\022\023\n\013blackListId\030\001 \001(\003\022\016\n\006userId\030\002 \001(\003\022\020\n" +
      "\010targetId\030\003 \001(\003\022\022\n\ntargetName\030\004 \001(\t\022\022\n\nc" +
      "reateTime\030\005 \001(\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BlackListInfoVO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BlackListInfoVO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BlackListInfoVO_descriptor,
        new String[] { "BlackListId", "UserId", "TargetId", "TargetName", "CreateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
