package com.happy.otc.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capitalLogInfo.proto

public final class CapitalLogInfo {
  private CapitalLogInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code CapitalLogType}
   */
  public enum CapitalLogType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     *买入
     * </pre>
     *
     * <code>BUY = 1;</code>
     */
    BUY(1),
    /**
     * <pre>
     *卖出
     * </pre>
     *
     * <code>SELL = 2;</code>
     */
    SELL(2),
    /**
     * <pre>
     *充币
     * </pre>
     *
     * <code>CHARGE = 3;</code>
     */
    CHARGE(3),
    /**
     * <pre>
     *提币
     * </pre>
     *
     * <code>WITHDRAWALS = 4;</code>
     */
    WITHDRAWALS(4),
    /**
     * <pre>
     *资金冻结
     * </pre>
     *
     * <code>FROZEN = 5;</code>
     */
    FROZEN(5),
    /**
     * <pre>
     *资金解冻
     * </pre>
     *
     * <code>THAW = 6;</code>
     */
    THAW(6),
    /**
     * <pre>
     *OTC 账户资金划出
     * </pre>
     *
     * <code>OTC_OUT = 7;</code>
     */
    OTC_OUT(7),
    /**
     * <pre>
     *OTC 账户资金划入
     * </pre>
     *
     * <code>OTC_IN = 8;</code>
     */
    OTC_IN(8),
    /**
     * <pre>
     *资金划转
     * </pre>
     *
     * <code>OTC_TRANSFER = 9;</code>
     */
    OTC_TRANSFER(9),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     *买入
     * </pre>
     *
     * <code>BUY = 1;</code>
     */
    public static final int BUY_VALUE = 1;
    /**
     * <pre>
     *卖出
     * </pre>
     *
     * <code>SELL = 2;</code>
     */
    public static final int SELL_VALUE = 2;
    /**
     * <pre>
     *充币
     * </pre>
     *
     * <code>CHARGE = 3;</code>
     */
    public static final int CHARGE_VALUE = 3;
    /**
     * <pre>
     *提币
     * </pre>
     *
     * <code>WITHDRAWALS = 4;</code>
     */
    public static final int WITHDRAWALS_VALUE = 4;
    /**
     * <pre>
     *资金冻结
     * </pre>
     *
     * <code>FROZEN = 5;</code>
     */
    public static final int FROZEN_VALUE = 5;
    /**
     * <pre>
     *资金解冻
     * </pre>
     *
     * <code>THAW = 6;</code>
     */
    public static final int THAW_VALUE = 6;
    /**
     * <pre>
     *OTC 账户资金划出
     * </pre>
     *
     * <code>OTC_OUT = 7;</code>
     */
    public static final int OTC_OUT_VALUE = 7;
    /**
     * <pre>
     *OTC 账户资金划入
     * </pre>
     *
     * <code>OTC_IN = 8;</code>
     */
    public static final int OTC_IN_VALUE = 8;
    /**
     * <pre>
     *资金划转
     * </pre>
     *
     * <code>OTC_TRANSFER = 9;</code>
     */
    public static final int OTC_TRANSFER_VALUE = 9;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static CapitalLogType valueOf(int value) {
      return forNumber(value);
    }

    public static CapitalLogType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return BUY;
        case 2: return SELL;
        case 3: return CHARGE;
        case 4: return WITHDRAWALS;
        case 5: return FROZEN;
        case 6: return THAW;
        case 7: return OTC_OUT;
        case 8: return OTC_IN;
        case 9: return OTC_TRANSFER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CapitalLogType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CapitalLogType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CapitalLogType>() {
            public CapitalLogType findValueByNumber(int number) {
              return CapitalLogType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CapitalLogInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final CapitalLogType[] VALUES = values();

    public static CapitalLogType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CapitalLogType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CapitalLogType)
  }

  public interface CapitalLogVOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CapitalLogVO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>.CapitalLogType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>.CapitalLogType type = 1;</code>
     */
    CapitalLogType getType();

    /**
     * <pre>
     *币种
     * </pre>
     *
     * <code>string kind = 2;</code>
     */
    String getKind();
    /**
     * <pre>
     *币种
     * </pre>
     *
     * <code>string kind = 2;</code>
     */
    com.google.protobuf.ByteString
        getKindBytes();

    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     */
    long getCreateTime();

    /**
     * <pre>
     *数量
     * </pre>
     *
     * <code>double quantity = 4;</code>
     */
    double getQuantity();

    /**
     * <pre>
     *提币地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    String getAddress();
    /**
     * <pre>
     *提币地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     *手续费
     * </pre>
     *
     * <code>double fee = 6;</code>
     */
    double getFee();

    /**
     * <pre>
     *单价
     * </pre>
     *
     * <code>double price = 7;</code>
     */
    double getPrice();

    /**
     * <pre>
     *对方用户名
     * </pre>
     *
     * <code>string targetUsername = 8;</code>
     */
    String getTargetUsername();
    /**
     * <pre>
     *对方用户名
     * </pre>
     *
     * <code>string targetUsername = 8;</code>
     */
    com.google.protobuf.ByteString
        getTargetUsernameBytes();

    /**
     * <pre>
     *法币币种
     * </pre>
     *
     * <code>string relevantKind = 9;</code>
     */
    String getRelevantKind();
    /**
     * <pre>
     *法币币种
     * </pre>
     *
     * <code>string relevantKind = 9;</code>
     */
    com.google.protobuf.ByteString
        getRelevantKindBytes();
  }
  /**
   * Protobuf type {@code CapitalLogVO}
   */
  public  static final class CapitalLogVO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CapitalLogVO)
      CapitalLogVOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CapitalLogVO.newBuilder() to construct.
    private CapitalLogVO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CapitalLogVO() {
      type_ = 0;
      kind_ = "";
      createTime_ = 0L;
      quantity_ = 0D;
      address_ = "";
      fee_ = 0D;
      price_ = 0D;
      targetUsername_ = "";
      relevantKind_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CapitalLogVO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              kind_ = s;
              break;
            }
            case 24: {

              createTime_ = input.readInt64();
              break;
            }
            case 33: {

              quantity_ = input.readDouble();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 49: {

              fee_ = input.readDouble();
              break;
            }
            case 57: {

              price_ = input.readDouble();
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              targetUsername_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              relevantKind_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CapitalLogInfo.internal_static_CapitalLogVO_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CapitalLogInfo.internal_static_CapitalLogVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CapitalLogVO.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>.CapitalLogType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>.CapitalLogType type = 1;</code>
     */
    public CapitalLogType getType() {
      CapitalLogType result = CapitalLogType.valueOf(type_);
      return result == null ? CapitalLogType.UNRECOGNIZED : result;
    }

    public static final int KIND_FIELD_NUMBER = 2;
    private volatile Object kind_;
    /**
     * <pre>
     *币种
     * </pre>
     *
     * <code>string kind = 2;</code>
     */
    public String getKind() {
      Object ref = kind_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        kind_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *币种
     * </pre>
     *
     * <code>string kind = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKindBytes() {
      Object ref = kind_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        kind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 3;
    private long createTime_;
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>int64 createTime = 3;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int QUANTITY_FIELD_NUMBER = 4;
    private double quantity_;
    /**
     * <pre>
     *数量
     * </pre>
     *
     * <code>double quantity = 4;</code>
     */
    public double getQuantity() {
      return quantity_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile Object address_;
    /**
     * <pre>
     *提币地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *提币地址
     * </pre>
     *
     * <code>string address = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FEE_FIELD_NUMBER = 6;
    private double fee_;
    /**
     * <pre>
     *手续费
     * </pre>
     *
     * <code>double fee = 6;</code>
     */
    public double getFee() {
      return fee_;
    }

    public static final int PRICE_FIELD_NUMBER = 7;
    private double price_;
    /**
     * <pre>
     *单价
     * </pre>
     *
     * <code>double price = 7;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int TARGETUSERNAME_FIELD_NUMBER = 8;
    private volatile Object targetUsername_;
    /**
     * <pre>
     *对方用户名
     * </pre>
     *
     * <code>string targetUsername = 8;</code>
     */
    public String getTargetUsername() {
      Object ref = targetUsername_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        targetUsername_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *对方用户名
     * </pre>
     *
     * <code>string targetUsername = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTargetUsernameBytes() {
      Object ref = targetUsername_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        targetUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RELEVANTKIND_FIELD_NUMBER = 9;
    private volatile Object relevantKind_;
    /**
     * <pre>
     *法币币种
     * </pre>
     *
     * <code>string relevantKind = 9;</code>
     */
    public String getRelevantKind() {
      Object ref = relevantKind_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        relevantKind_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *法币币种
     * </pre>
     *
     * <code>string relevantKind = 9;</code>
     */
    public com.google.protobuf.ByteString
        getRelevantKindBytes() {
      Object ref = relevantKind_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        relevantKind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != CapitalLogType.UNKNOWN.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getKindBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, kind_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(3, createTime_);
      }
      if (quantity_ != 0D) {
        output.writeDouble(4, quantity_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      if (fee_ != 0D) {
        output.writeDouble(6, fee_);
      }
      if (price_ != 0D) {
        output.writeDouble(7, price_);
      }
      if (!getTargetUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, targetUsername_);
      }
      if (!getRelevantKindBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, relevantKind_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != CapitalLogType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getKindBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, kind_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, createTime_);
      }
      if (quantity_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, quantity_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      if (fee_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, fee_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, price_);
      }
      if (!getTargetUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, targetUsername_);
      }
      if (!getRelevantKindBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, relevantKind_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CapitalLogVO)) {
        return super.equals(obj);
      }
      CapitalLogVO other = (CapitalLogVO) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getKind()
          .equals(other.getKind());
      result = result && (getCreateTime()
          == other.getCreateTime());
      result = result && (
          Double.doubleToLongBits(getQuantity())
          == Double.doubleToLongBits(
              other.getQuantity()));
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && (
          Double.doubleToLongBits(getFee())
          == Double.doubleToLongBits(
              other.getFee()));
      result = result && (
          Double.doubleToLongBits(getPrice())
          == Double.doubleToLongBits(
              other.getPrice()));
      result = result && getTargetUsername()
          .equals(other.getTargetUsername());
      result = result && getRelevantKind()
          .equals(other.getRelevantKind());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + KIND_FIELD_NUMBER;
      hash = (53 * hash) + getKind().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getQuantity()));
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + FEE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getFee()));
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + TARGETUSERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTargetUsername().hashCode();
      hash = (37 * hash) + RELEVANTKIND_FIELD_NUMBER;
      hash = (53 * hash) + getRelevantKind().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CapitalLogVO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CapitalLogVO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CapitalLogVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CapitalLogVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CapitalLogVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CapitalLogVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CapitalLogVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CapitalLogVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CapitalLogVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CapitalLogVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CapitalLogVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CapitalLogVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CapitalLogVO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CapitalLogVO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CapitalLogVO)
        CapitalLogVOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CapitalLogInfo.internal_static_CapitalLogVO_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CapitalLogInfo.internal_static_CapitalLogVO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CapitalLogVO.class, Builder.class);
      }

      // Construct using CapitalLogInfo.CapitalLogVO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        kind_ = "";

        createTime_ = 0L;

        quantity_ = 0D;

        address_ = "";

        fee_ = 0D;

        price_ = 0D;

        targetUsername_ = "";

        relevantKind_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CapitalLogInfo.internal_static_CapitalLogVO_descriptor;
      }

      public CapitalLogVO getDefaultInstanceForType() {
        return CapitalLogVO.getDefaultInstance();
      }

      public CapitalLogVO build() {
        CapitalLogVO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CapitalLogVO buildPartial() {
        CapitalLogVO result = new CapitalLogVO(this);
        result.type_ = type_;
        result.kind_ = kind_;
        result.createTime_ = createTime_;
        result.quantity_ = quantity_;
        result.address_ = address_;
        result.fee_ = fee_;
        result.price_ = price_;
        result.targetUsername_ = targetUsername_;
        result.relevantKind_ = relevantKind_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CapitalLogVO) {
          return mergeFrom((CapitalLogVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CapitalLogVO other) {
        if (other == CapitalLogVO.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getKind().isEmpty()) {
          kind_ = other.kind_;
          onChanged();
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getQuantity() != 0D) {
          setQuantity(other.getQuantity());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.getFee() != 0D) {
          setFee(other.getFee());
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (!other.getTargetUsername().isEmpty()) {
          targetUsername_ = other.targetUsername_;
          onChanged();
        }
        if (!other.getRelevantKind().isEmpty()) {
          relevantKind_ = other.relevantKind_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CapitalLogVO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CapitalLogVO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.CapitalLogType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.CapitalLogType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.CapitalLogType type = 1;</code>
       */
      public CapitalLogType getType() {
        CapitalLogType result = CapitalLogType.valueOf(type_);
        return result == null ? CapitalLogType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.CapitalLogType type = 1;</code>
       */
      public Builder setType(CapitalLogType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.CapitalLogType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object kind_ = "";
      /**
       * <pre>
       *币种
       * </pre>
       *
       * <code>string kind = 2;</code>
       */
      public String getKind() {
        Object ref = kind_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          kind_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *币种
       * </pre>
       *
       * <code>string kind = 2;</code>
       */
      public com.google.protobuf.ByteString
          getKindBytes() {
        Object ref = kind_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          kind_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *币种
       * </pre>
       *
       * <code>string kind = 2;</code>
       */
      public Builder setKind(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *币种
       * </pre>
       *
       * <code>string kind = 2;</code>
       */
      public Builder clearKind() {
        
        kind_ = getDefaultInstance().getKind();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *币种
       * </pre>
       *
       * <code>string kind = 2;</code>
       */
      public Builder setKindBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kind_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>int64 createTime = 3;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>int64 createTime = 3;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>int64 createTime = 3;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private double quantity_ ;
      /**
       * <pre>
       *数量
       * </pre>
       *
       * <code>double quantity = 4;</code>
       */
      public double getQuantity() {
        return quantity_;
      }
      /**
       * <pre>
       *数量
       * </pre>
       *
       * <code>double quantity = 4;</code>
       */
      public Builder setQuantity(double value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数量
       * </pre>
       *
       * <code>double quantity = 4;</code>
       */
      public Builder clearQuantity() {
        
        quantity_ = 0D;
        onChanged();
        return this;
      }

      private Object address_ = "";
      /**
       * <pre>
       *提币地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *提币地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *提币地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提币地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提币地址
       * </pre>
       *
       * <code>string address = 5;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private double fee_ ;
      /**
       * <pre>
       *手续费
       * </pre>
       *
       * <code>double fee = 6;</code>
       */
      public double getFee() {
        return fee_;
      }
      /**
       * <pre>
       *手续费
       * </pre>
       *
       * <code>double fee = 6;</code>
       */
      public Builder setFee(double value) {
        
        fee_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手续费
       * </pre>
       *
       * <code>double fee = 6;</code>
       */
      public Builder clearFee() {
        
        fee_ = 0D;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <pre>
       *单价
       * </pre>
       *
       * <code>double price = 7;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <pre>
       *单价
       * </pre>
       *
       * <code>double price = 7;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *单价
       * </pre>
       *
       * <code>double price = 7;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }

      private Object targetUsername_ = "";
      /**
       * <pre>
       *对方用户名
       * </pre>
       *
       * <code>string targetUsername = 8;</code>
       */
      public String getTargetUsername() {
        Object ref = targetUsername_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          targetUsername_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *对方用户名
       * </pre>
       *
       * <code>string targetUsername = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTargetUsernameBytes() {
        Object ref = targetUsername_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          targetUsername_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *对方用户名
       * </pre>
       *
       * <code>string targetUsername = 8;</code>
       */
      public Builder setTargetUsername(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        targetUsername_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对方用户名
       * </pre>
       *
       * <code>string targetUsername = 8;</code>
       */
      public Builder clearTargetUsername() {
        
        targetUsername_ = getDefaultInstance().getTargetUsername();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对方用户名
       * </pre>
       *
       * <code>string targetUsername = 8;</code>
       */
      public Builder setTargetUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        targetUsername_ = value;
        onChanged();
        return this;
      }

      private Object relevantKind_ = "";
      /**
       * <pre>
       *法币币种
       * </pre>
       *
       * <code>string relevantKind = 9;</code>
       */
      public String getRelevantKind() {
        Object ref = relevantKind_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          relevantKind_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *法币币种
       * </pre>
       *
       * <code>string relevantKind = 9;</code>
       */
      public com.google.protobuf.ByteString
          getRelevantKindBytes() {
        Object ref = relevantKind_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          relevantKind_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *法币币种
       * </pre>
       *
       * <code>string relevantKind = 9;</code>
       */
      public Builder setRelevantKind(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        relevantKind_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *法币币种
       * </pre>
       *
       * <code>string relevantKind = 9;</code>
       */
      public Builder clearRelevantKind() {
        
        relevantKind_ = getDefaultInstance().getRelevantKind();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *法币币种
       * </pre>
       *
       * <code>string relevantKind = 9;</code>
       */
      public Builder setRelevantKindBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        relevantKind_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CapitalLogVO)
    }

    // @@protoc_insertion_point(class_scope:CapitalLogVO)
    private static final CapitalLogVO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CapitalLogVO();
    }

    public static CapitalLogVO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CapitalLogVO>
        PARSER = new com.google.protobuf.AbstractParser<CapitalLogVO>() {
      public CapitalLogVO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CapitalLogVO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CapitalLogVO> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CapitalLogVO> getParserForType() {
      return PARSER;
    }

    public CapitalLogVO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CapitalLogRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CapitalLogRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>.CapitalLogType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>.CapitalLogType type = 1;</code>
     */
    CapitalLogType getType();

    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>string time = 2;</code>
     */
    String getTime();
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>string time = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <pre>
     *币种
     * </pre>
     *
     * <code>int64 kind = 3;</code>
     */
    long getKind();

    /**
     * <pre>
     *当前页
     * </pre>
     *
     * <code>int32 pageIndex = 4;</code>
     */
    int getPageIndex();

    /**
     * <pre>
     *每页数量
     * </pre>
     *
     * <code>int32 pageSize = 5;</code>
     */
    int getPageSize();

    /**
     * <pre>
     *时区
     * </pre>
     *
     * <code>int32 timeZone = 6;</code>
     */
    int getTimeZone();
  }
  /**
   * Protobuf type {@code CapitalLogRequest}
   */
  public  static final class CapitalLogRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CapitalLogRequest)
      CapitalLogRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CapitalLogRequest.newBuilder() to construct.
    private CapitalLogRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CapitalLogRequest() {
      type_ = 0;
      time_ = "";
      kind_ = 0L;
      pageIndex_ = 0;
      pageSize_ = 0;
      timeZone_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CapitalLogRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            case 24: {

              kind_ = input.readInt64();
              break;
            }
            case 32: {

              pageIndex_ = input.readInt32();
              break;
            }
            case 40: {

              pageSize_ = input.readInt32();
              break;
            }
            case 48: {

              timeZone_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CapitalLogInfo.internal_static_CapitalLogRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CapitalLogInfo.internal_static_CapitalLogRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CapitalLogRequest.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>.CapitalLogType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *类型
     * </pre>
     *
     * <code>.CapitalLogType type = 1;</code>
     */
    public CapitalLogType getType() {
      CapitalLogType result = CapitalLogType.valueOf(type_);
      return result == null ? CapitalLogType.UNRECOGNIZED : result;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private volatile Object time_;
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>string time = 2;</code>
     */
    public String getTime() {
      Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *时间
     * </pre>
     *
     * <code>string time = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KIND_FIELD_NUMBER = 3;
    private long kind_;
    /**
     * <pre>
     *币种
     * </pre>
     *
     * <code>int64 kind = 3;</code>
     */
    public long getKind() {
      return kind_;
    }

    public static final int PAGEINDEX_FIELD_NUMBER = 4;
    private int pageIndex_;
    /**
     * <pre>
     *当前页
     * </pre>
     *
     * <code>int32 pageIndex = 4;</code>
     */
    public int getPageIndex() {
      return pageIndex_;
    }

    public static final int PAGESIZE_FIELD_NUMBER = 5;
    private int pageSize_;
    /**
     * <pre>
     *每页数量
     * </pre>
     *
     * <code>int32 pageSize = 5;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    public static final int TIMEZONE_FIELD_NUMBER = 6;
    private int timeZone_;
    /**
     * <pre>
     *时区
     * </pre>
     *
     * <code>int32 timeZone = 6;</code>
     */
    public int getTimeZone() {
      return timeZone_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != CapitalLogType.UNKNOWN.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, time_);
      }
      if (kind_ != 0L) {
        output.writeInt64(3, kind_);
      }
      if (pageIndex_ != 0) {
        output.writeInt32(4, pageIndex_);
      }
      if (pageSize_ != 0) {
        output.writeInt32(5, pageSize_);
      }
      if (timeZone_ != 0) {
        output.writeInt32(6, timeZone_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != CapitalLogType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, time_);
      }
      if (kind_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, kind_);
      }
      if (pageIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pageIndex_);
      }
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, pageSize_);
      }
      if (timeZone_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, timeZone_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CapitalLogRequest)) {
        return super.equals(obj);
      }
      CapitalLogRequest other = (CapitalLogRequest) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getTime()
          .equals(other.getTime());
      result = result && (getKind()
          == other.getKind());
      result = result && (getPageIndex()
          == other.getPageIndex());
      result = result && (getPageSize()
          == other.getPageSize());
      result = result && (getTimeZone()
          == other.getTimeZone());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (37 * hash) + KIND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getKind());
      hash = (37 * hash) + PAGEINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getPageIndex();
      hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (37 * hash) + TIMEZONE_FIELD_NUMBER;
      hash = (53 * hash) + getTimeZone();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CapitalLogRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CapitalLogRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CapitalLogRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CapitalLogRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CapitalLogRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CapitalLogRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CapitalLogRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CapitalLogRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CapitalLogRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CapitalLogRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CapitalLogRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CapitalLogRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CapitalLogRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CapitalLogRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CapitalLogRequest)
        CapitalLogRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CapitalLogInfo.internal_static_CapitalLogRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CapitalLogInfo.internal_static_CapitalLogRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CapitalLogRequest.class, Builder.class);
      }

      // Construct using CapitalLogInfo.CapitalLogRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        time_ = "";

        kind_ = 0L;

        pageIndex_ = 0;

        pageSize_ = 0;

        timeZone_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CapitalLogInfo.internal_static_CapitalLogRequest_descriptor;
      }

      public CapitalLogRequest getDefaultInstanceForType() {
        return CapitalLogRequest.getDefaultInstance();
      }

      public CapitalLogRequest build() {
        CapitalLogRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CapitalLogRequest buildPartial() {
        CapitalLogRequest result = new CapitalLogRequest(this);
        result.type_ = type_;
        result.time_ = time_;
        result.kind_ = kind_;
        result.pageIndex_ = pageIndex_;
        result.pageSize_ = pageSize_;
        result.timeZone_ = timeZone_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CapitalLogRequest) {
          return mergeFrom((CapitalLogRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CapitalLogRequest other) {
        if (other == CapitalLogRequest.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        if (other.getKind() != 0L) {
          setKind(other.getKind());
        }
        if (other.getPageIndex() != 0) {
          setPageIndex(other.getPageIndex());
        }
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        if (other.getTimeZone() != 0) {
          setTimeZone(other.getTimeZone());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CapitalLogRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CapitalLogRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.CapitalLogType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.CapitalLogType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.CapitalLogType type = 1;</code>
       */
      public CapitalLogType getType() {
        CapitalLogType result = CapitalLogType.valueOf(type_);
        return result == null ? CapitalLogType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.CapitalLogType type = 1;</code>
       */
      public Builder setType(CapitalLogType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.CapitalLogType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object time_ = "";
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>string time = 2;</code>
       */
      public String getTime() {
        Object ref = time_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>string time = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>string time = 2;</code>
       */
      public Builder setTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>string time = 2;</code>
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间
       * </pre>
       *
       * <code>string time = 2;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }

      private long kind_ ;
      /**
       * <pre>
       *币种
       * </pre>
       *
       * <code>int64 kind = 3;</code>
       */
      public long getKind() {
        return kind_;
      }
      /**
       * <pre>
       *币种
       * </pre>
       *
       * <code>int64 kind = 3;</code>
       */
      public Builder setKind(long value) {
        
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *币种
       * </pre>
       *
       * <code>int64 kind = 3;</code>
       */
      public Builder clearKind() {
        
        kind_ = 0L;
        onChanged();
        return this;
      }

      private int pageIndex_ ;
      /**
       * <pre>
       *当前页
       * </pre>
       *
       * <code>int32 pageIndex = 4;</code>
       */
      public int getPageIndex() {
        return pageIndex_;
      }
      /**
       * <pre>
       *当前页
       * </pre>
       *
       * <code>int32 pageIndex = 4;</code>
       */
      public Builder setPageIndex(int value) {
        
        pageIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前页
       * </pre>
       *
       * <code>int32 pageIndex = 4;</code>
       */
      public Builder clearPageIndex() {
        
        pageIndex_ = 0;
        onChanged();
        return this;
      }

      private int pageSize_ ;
      /**
       * <pre>
       *每页数量
       * </pre>
       *
       * <code>int32 pageSize = 5;</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <pre>
       *每页数量
       * </pre>
       *
       * <code>int32 pageSize = 5;</code>
       */
      public Builder setPageSize(int value) {
        
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *每页数量
       * </pre>
       *
       * <code>int32 pageSize = 5;</code>
       */
      public Builder clearPageSize() {
        
        pageSize_ = 0;
        onChanged();
        return this;
      }

      private int timeZone_ ;
      /**
       * <pre>
       *时区
       * </pre>
       *
       * <code>int32 timeZone = 6;</code>
       */
      public int getTimeZone() {
        return timeZone_;
      }
      /**
       * <pre>
       *时区
       * </pre>
       *
       * <code>int32 timeZone = 6;</code>
       */
      public Builder setTimeZone(int value) {
        
        timeZone_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时区
       * </pre>
       *
       * <code>int32 timeZone = 6;</code>
       */
      public Builder clearTimeZone() {
        
        timeZone_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CapitalLogRequest)
    }

    // @@protoc_insertion_point(class_scope:CapitalLogRequest)
    private static final CapitalLogRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CapitalLogRequest();
    }

    public static CapitalLogRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CapitalLogRequest>
        PARSER = new com.google.protobuf.AbstractParser<CapitalLogRequest>() {
      public CapitalLogRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CapitalLogRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CapitalLogRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CapitalLogRequest> getParserForType() {
      return PARSER;
    }

    public CapitalLogRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CapitalLogVO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CapitalLogVO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CapitalLogRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CapitalLogRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024capitalLogInfo.proto\"\274\001\n\014CapitalLogVO\022" +
      "\035\n\004type\030\001 \001(\0162\017.CapitalLogType\022\014\n\004kind\030\002" +
      " \001(\t\022\022\n\ncreateTime\030\003 \001(\003\022\020\n\010quantity\030\004 \001" +
      "(\001\022\017\n\007address\030\005 \001(\t\022\013\n\003fee\030\006 \001(\001\022\r\n\005pric" +
      "e\030\007 \001(\001\022\026\n\016targetUsername\030\010 \001(\t\022\024\n\014relev" +
      "antKind\030\t \001(\t\"\205\001\n\021CapitalLogRequest\022\035\n\004t" +
      "ype\030\001 \001(\0162\017.CapitalLogType\022\014\n\004time\030\002 \001(\t" +
      "\022\014\n\004kind\030\003 \001(\003\022\021\n\tpageIndex\030\004 \001(\005\022\020\n\010pag" +
      "eSize\030\005 \001(\005\022\020\n\010timeZone\030\006 \001(\005*\216\001\n\016Capita" +
      "lLogType\022\013\n\007UNKNOWN\020\000\022\007\n\003BUY\020\001\022\010\n\004SELL\020\002" +
      "\022\n\n\006CHARGE\020\003\022\017\n\013WITHDRAWALS\020\004\022\n\n\006FROZEN\020" +
      "\005\022\010\n\004THAW\020\006\022\013\n\007OTC_OUT\020\007\022\n\n\006OTC_IN\020\010\022\020\n\014" +
      "OTC_TRANSFER\020\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CapitalLogVO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CapitalLogVO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CapitalLogVO_descriptor,
        new String[] { "Type", "Kind", "CreateTime", "Quantity", "Address", "Fee", "Price", "TargetUsername", "RelevantKind", });
    internal_static_CapitalLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CapitalLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CapitalLogRequest_descriptor,
        new String[] { "Type", "Time", "Kind", "PageIndex", "PageSize", "TimeZone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
